### ISSUE TITLE
「Request」《Teaming - WorldGuard Compatibility》

### ISSUE THREAD

**Issue by linsaftw** [Photon-GitHub/AntiCheatAddition#185]
Hello, I would like to request a feature for the next versions about WorldGuard compatibility for the Teaming check.

I love the idea of Kicking players teaming because is a big issue in FFA servers like mine, but setting up 30+ safezones just to prevent teaming its really annoying.

So i would like to request a option in the config to enable a WorldGuard hook that checks if: PvP <allow or not set> / invincible <deny or not set>.

This will make the config A LOT easier for multiworlds FFA, but also for HCF servers and RPG servers.

Example config:

`
Teaming:
WorldGuard: true # Hook with WorldGuard Regions
`

Thanks for reading 👍

**Comment by Photon-GitHub** [comment]
Added in 9.0.0.
