### ISSUE TITLE
Liteloader 

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AntiCheatAddition#268]
Please include:
- Server version: 1.12.2
- ProtocolLib version: latest build
- The version of AACAdditionPro: 4.2.0
- A detailed description of the bug / wanted feature: 

    hello, the version 4.2.0 don't work for liteloader 1.12.2, the version AACAdditionPro-4.1.1 is better and kick liteloader 1.12.2 can you fix this? (i have test this)
- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
Can you please post your config (or send it to me via pm if you don't want to publish it)?

**Comment by leoncp9** [comment]
i don't have config of 4.2.0 because don't work for liteloader but i send you a same config but of 4.1.1

download
https://drive.google.com/open?id=1HFys4KG7XWivl_2ODV7JsR-CRF3tYMGo

**Comment by leoncp9** [comment]
i use this plugin only for liteloader no for other hack, so  i set all config to false, and i set only true mods not alloed on my server

**Comment by Photon-GitHub** [comment]
All ClientControl commands are not loaded correctly.
