### ISSUE TITLE
Suggestion for the teaming check

### ISSUE THREAD

**Issue by iMaarten** [Photon-GitHub/AntiCheatAddition#275]
Please include:
- Wanted feature: A way for Factions and Gangs to bypass the teaming check.
     - Add bypass support for https://www.spigotmc.org/resources/factionsuuid.1035/
     - Add bypass support for https://www.spigotmc.org/resources/gangs.2604/
     - Add a separate bypass permission for staff

**Comment by Photon-GitHub** [comment]
@iMaarten I already offer a seperate bypass permission (AACAdditionPro.bypass.teaming)

**Comment by Photon-GitHub** [comment]
I will not implement this further as there are quite a few similar plugins, and hooking each of them would be problematic. You can use ACA's API to bypass the relevant players.
