### ISSUE TITLE
ESP-check doesn't work

### ISSUE THREAD

**Issue by Pesticidus** [Photon-GitHub/AntiCheatAddition#411]
If I understand correctly, then the player should hide at least when he is sneaking
But I don’t see it working. Maybe I'm doing something wrong.

Video: https://youtu.be/LJeoT2kPlhY
Config: https://pastebin.com/QgnxLw03

Paper: 1.12.2
AACAP: 6.3.1
Other plugins: ProtocolLib, Essentials

**Comment by taljafox** [comment]
Yo you do realise anti esp is for new versions of minecraft right? 1.16+ or 1.15+ around there

**Comment by Janmm14** [comment]
> Yo you do realise anti esp is for new versions of minecraft right? 1.16+ or 1.15+ around there

Esp check is meant to work for all minecraft versions AACAdditionPro supports.

**Comment by PestAnaLiz** [comment]
Still not working (latest AACAP, spigot 1.12.2)
https://youtu.be/enIrnUn889Q

**Comment by Photon-GitHub** [comment]
Should be fixed by now.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity and newer, similar issues.
