### ISSUE TITLE
PingSpoof false positives

### ISSUE THREAD

**Issue by untuned** [Photon-GitHub/AntiCheatAddition#467]
Almost all of my players are getting false flagged for PingSpoof. The configuration I'm using is Celebrimbor's Ghost (optimized AACAP), and we are running on a Bungeecord network.

![example](https://untnd.me/XT_mB1tcP)

**Comment by Photon-GitHub** [comment]
Please add your logs of AACAdditionPro.

**Comment by untuned** [comment]
> Please add your logs of AACAdditionPro.

Here you go.
[2021-07-12.log](https://github.com/Photon-GitHub/AACAdditionPro/files/6803933/2021-07-12.log)

**Comment by Janmm14** [comment]
Lower spoofed ping than real ping is something impossible. "real ping" measurement must be highly inaccurate here.

**Comment by iFlamingoz** [comment]
+1

**Comment by untuned** [comment]
AAC is no longer supported so I am closing this.
