### ISSUE TITLE
AAC hook not working properly

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#472]
6.5.3:
![image](https://user-images.githubusercontent.com/35672743/145811279-90b6864a-f3a9-40a0-beb0-fcc4b18fd273.png)
7.1.2:
![image](https://user-images.githubusercontent.com/35672743/145811317-6f7e6019-15c8-4a35-97f9-7f50ba85ac5c.png)

Server Information:
  Server Ver: PaperSpigot 1.8.8
  AACAdditionPro Ver: 7.1.4
  AAC Ver: 5.1.0
  Protocollib Ver: 4.7.0

**Comment by iFlamingoz** [comment]
Seems like this might be the case for commands on modules as well.
Without AAC: https://prnt.sc/1fm2u0a 
With: https://prnt.sc/1fm5crv

**Comment by Photon-GitHub** [comment]
Yes, that is intended behaviour, just read the config comments:

# If this option is active and AAC is installed AACAdditionPro will not execute any commands specified above and instead
# hooks the AAC feature system to allow you to specify punishments via the AAC config.
# This way, AACAdditionPro's checks will also appear in AAC's status messages.

I mean, I could add an option to still execute the commands, but that would kind of defeat the purpose of AAC integration…

**Comment by iFlamingoz** [comment]
Alright thought sentinel commands should execute even if AAC was hooked

**Comment by Photon-GitHub** [comment]
You can access the sentinel modules just like any other in the AAC config and punish there.

**Comment by iFlamingoz** [comment]
Thresholds don't seem to be executing even when in the AAC config? (tested using default Celebrimbour's optimized configs)

**[AACAdditionPro] IFlamingoz
[AACAdditionPro] Inventory -> vl 591
[AACAdditionPro] Inventory.parts.Move -> vl 579
[AACAdditionPro] Scaffold -> vl 483**

**Comment by Janmm14** [comment]
I think theres a maximum of VLs AAC 5 allows per check.

**Comment by iFlamingoz** [comment]
Those checks are supposed to execute at 120 vl.

**Comment by Photon-GitHub** [comment]
Indeed, version 7 unified the module system. Before, Sentinel was not hooked into AAC and used a different system compared to the regular checks. This was one of the motivators of version 7, in which modules are much easier to add.

**Comment by iFlamingoz** [comment]
> Indeed, version 7 unified the module system. Before, Sentinel was not hooked into AAC and used a different system compared to the regular checks. This was one of the motivators of version 7, in which modules are much easier to add.

Yes, however, aren't checks like Inventory move supposed to run thresholds from the AAC config and be displayed in a players AAC status message?

6.5.3: 
![image](https://user-images.githubusercontent.com/35672743/137613469-055be7d4-693d-41fe-9cdd-2a3eb4574f8d.png)

7.1.2:
![image](https://user-images.githubusercontent.com/35672743/137613596-8521ebf4-ed68-4699-b4bb-bb0c60a31acf.png)

**Comment by iFlamingoz** [comment]
> That is indeed a bug if you enabled the hook in the config.

Yes, the hook is enabled and the only check (out of the ones I have tested) that seem to run thresholds and show up in peoples AAC status messages is the PingSpoof check.

**Comment by Photon-GitHub** [comment]
@iFlamingoz could you please pm me your AAC and AACAdditionPro configs? (On Discord / Spigot)

**Comment by iFlamingoz** [comment]
> @iFlamingoz could you please pm me your AAC and AACAdditionPro configs? (On Discord / Spigot)

Done (on discord)

**Comment by Photon-GitHub** [comment]
AAC Hook has been removed in 8.0.0 as AAC is no longer maintained.
