### ISSUE TITLE
ESP not working properly

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#488]
Video: https://youtu.be/-Mhe1-r5ga0
An Error that gets spammed randomly: https://pastebin.com/cdtmiQyM

Server version: 1.8.8 PaperSpigot
AACADP Version: 7.3.2

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.0.0

**Comment by iFlamingoz** [comment]
> Should be fixed in 8.0.0

The error keeps persisting in 8.0.3. (https://pastebin.com/mMTvEg3F)

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.0.5

**Comment by iFlamingoz** [comment]
> Should be fixed in 8.0.5 (hopefully)

https://youtu.be/gAf7IGOstNw
Esp.calculate_third_person_modes is turned on.
