### ISSUE TITLE
Error on startup (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#503]
Error: https://pastebin.com/rwL78sPh

ACA Version: 8.0.5
Server Version: PaperSpigot 1.8.8

**Comment by Photon-GitHub** [comment]
Urgh, 1.8 has an ancient guava that doesn't have those methods...

**Comment by Photon-GitHub** [comment]
Should be fixed with 8.0.6
