### ISSUE TITLE
ESP - Hidden players not reappearing when switching to creative/spectator

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#505]
https://youtu.be/f0LrTLtavDE

ACA Version: 8.0.6
Server Version: 1.8.8 PaperSpigot

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.0.7.

**Comment by iFlamingoz** [comment]
> Should be fixed in 8.0.7.

The issue persists in 8.0.7.

**Comment by Photon-GitHub** [comment]
Is this still happening?

**Comment by iFlamingoz** [comment]
> Is this still happening?

Yes.

**Comment by iFlamingoz** [comment]
This might be a better video showcasing the bug: https://youtu.be/ZpeVG2N_BYY

**Comment by Photon-GitHub** [comment]
8.3.3 now fully processes players regardless of gamemode, so this should be fixed.
