### ISSUE TITLE
[Feature Request] Option to ignore sneaking condition in ESP

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#507]
Add an option to ignore whether a person is crouching or not when hiding players in esp as people might not care about the name tags.

**Comment by Photon-GitHub** [comment]
You mean have an "only hide equipment option"?
Why would anyone want to enable that? After all, ESP could show the position of the player. Nametags are not visible when sneaking behind blocks.

**Comment by iFlamingoz** [comment]
No, I mean a "hide players even if they're not sneaking" option.

**Comment by Photon-GitHub** [comment]
Added in 8.2.0
