### ISSUE TITLE
PacketAnalysis EqualRotation False Positive

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#508]
PacketAnalysis EqualRotation false positives whenever a newer version of the game right-clicks an item and moves.
https://youtu.be/lkHuQ4leirA
https://pastebin.com/8MGNmJaP

ACA: 8.0.7
Client: 1.18.2
Server: 1.8.8 PaperSpigot
ViaVersions: 4.2.1

**Comment by iFlamingoz** [comment]
It seems like it also falses on 1.18 servers.
https://youtu.be/4aOWJIw1N-8

**Comment by Janmm14** [comment]
Ah yeah 1.17+ clients can false this.
