### ISSUE TITLE
FastSwitch false positive when using items

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#519]
https://youtu.be/izqJcgQ6u20

ACA:  8.1.0
Server Version: 1.8.8

**Comment by Photon-GitHub** [comment]
Yes, this is kind of the point of the check. If you switch very quickly between items and do not scoll, which is behaviour that often appears when multple cheats like killaura and scaffold are active at the same time. A player can emulate this with lots of spamming hotbar keys, but I do not see when a normal player would do that for extended periods of time.

**Comment by Photon-GitHub** [comment]
Unless players actually use this, I will close it as wontfix for now. Feel free to reopen if you have more info on how one would use this except purposefully triggering the AC.
