### ISSUE TITLE
Extreme speeds cause scaffold false positives

### ISSUE THREAD

**Issue by iFlamingoz** [Photon-GitHub/AntiCheatAddition#522]
Video: https://youtu.be/TClQ6pStMOA
Logs: https://pastebin.com/bQh3wYU8

**Comment by Photon-GitHub** [comment]
I cannot reproduce these with a vanilla client. Please recheck if this is also happening on vanilla.

**Comment by iFlamingoz** [comment]
> I cannot reproduce these with a vanilla client. Please recheck if this is also happening on vanilla. I tested speed 25, 50 and 127.

Yes, I can reproduce this just fine with a vanilla client (1.8.9) and a PaperSpigot server (1.8.8).
I can reproduce this with a speed of 100.

**Comment by iFlamingoz** [comment]
> I cannot reproduce these with a vanilla client. Please recheck if this is also happening on vanilla. I tested speed 25, 50 and 127.

Also, I am not able to start the server without manually creating the logs folder.
Error: https://pastebin.com/4dBJMP0n

**Comment by Photon-GitHub** [comment]
Fixed in 8.4.1
