### ISSUE TITLE
Way to prevent auto totem switch while not effecting inventory or chest sorting?

### ISSUE THREAD

**Issue by Moranyixiao** [Photon-GitHub/AntiCheatAddition#527]
Hi just wanna know is there a way to prevent off-hand auto totem switch 
while the inventory or chest sorting mod can still be use?

**Comment by Photon-GitHub** [comment]
I would recommend you using ACA‘s api. After all, your usecase is quite special and covered by inventory. Now you just need to cancel the violations from normal chest stealing, which is best done via the api.
