### ISSUE TITLE
ACA is not working on 1.19

### ISSUE THREAD

**Issue by sergeyshadok** [Photon-GitHub/AntiCheatAddition#528]
My server was updated to 1.19 and this is unfortunately the only plugin that is not working with new version right now. Any plans on updating?

**Comment by Photon-GitHub** [comment]
Yes, I do plan on updating. However, right now ProtocolLib has not been updated to 1.19 and therefore I cannot update ACA. Most preparations for the update are already done, so I expect that I will be able to update soon.

**Comment by sergeyshadok** [comment]
> Yes, I do plan on updating. However, right now ProtocolLib has not been updated to 1.19 and therefore I cannot update ACA. Most preparations for the update are already done, so I expect that I will be able to update soon.

I think that ProtocolLib was updated to 1.19 7 days ago, according to last pom.xml commit
(https://github.com/dmulloy2/ProtocolLib)

Also I think that latest dev build in it's CI is for 1.19
(https://ci.dmulloy2.net/job/ProtocolLib/569/)

**Comment by Photon-GitHub** [comment]
That is not a stable release, but I could use it. I don’t know how many bugs that will cause though. Let’s see.

**Comment by Photon-GitHub** [comment]
Done.

**Comment by sergeyshadok** [comment]
Thank you! :)
