### ISSUE TITLE
Add support for Java 16

### ISSUE THREAD

**Issue by Chumb3x** [Photon-GitHub/AntiCheatAddition#529]
I have read that it is only available for only Java 17. Could you please add support for Java 16

**Comment by Photon-GitHub** [comment]
Java 16 has been unsupported for quite done time now and won’t get security updates, contrary to java 17 which is a long term support version. I don’t want to incentivise the use of insecure java versions, so I sadly won’t add support for java 16. Please update to java 17, also for the security of your server.
