### ISSUE TITLE
ESP doesnt work

### ISSUE THREAD

**Issue by BottledFish** [Photon-GitHub/AntiCheatAddition#533]
I am running ACA on paper 1.19, and most of the other checks work. However, ESP does not hide the player even when they are behind a wall.

Config: https://pastebin.com/iebj8utk
Screenshots: https://imgur.com/a/WkY0ufH

**Comment by Photon-GitHub** [comment]
Please add ACA‘s log file with the debug file level set to ALL, as I described in the discord support channel.

**Comment by BottledFish** [comment]
Here ya go
https://pastebin.com/CqbfgauB

**Comment by Janmm14** [comment]
In he log file comment you deleted it said esp is disabled in config.

**Comment by BottledFish** [comment]
hadnt realized it wasnt on

**Comment by BottledFish** [comment]
ok it works but it is soo buggy

**Comment by BottledFish** [comment]
anti esp in action: https://youtu.be/xmkXKjynjiA
log: https://pastebin.com/Lx98hSYd

**Comment by Photon-GitHub** [comment]
Fixed as discussed in discord.
