### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hyronymos1337** [Photon-GitHub/AntiCheatAddition#535]
Error: https://privatebin.net/?238079654c6bece2#5a61sVnjCQQHW9M38a52JuWW8n7CyjDXMcPHzCjaXc9n
Full-Server-Log: https://privatebin.net/?0e53045368a9c44f#5e6wogbpULqi4B9fx7FordUCsT4eewKzZHiC8FZGQNyp

Server-Version: 1.8.9 NachoSpigot
Protocollib-Version: Latest 5.0 Devbuild

**Comment by Photon-GitHub** [comment]
Err, sorry, but there is an error message that the log is not or no longer valid.

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.3.1
