### ISSUE TITLE
'Inventory check' cannot be disabled in the configuration and cannot be bypassed using permissions

### ISSUE THREAD

**Issue by Illusionika** [Photon-GitHub/AntiCheatAddition#546]
'Inventory check' is disabled in the configuration file, but it still works,I'm using the 'Inventory Profiles Next' mod
and use luckperms, adding 'anticheataddition.bypass.anticheataddition_inventory' ,This permission also does not work

purpur-1.19.3-1912
ACA 8.3.3
ProtocolLib #608

**Comment by Photon-GitHub** [comment]
This is a problem of the current architecture of my plugin. It will probably take some time to fix. In the meantime, you should be able to disable and bypass inventory completely by disabling not only inventory, but also every submodule and using the additional permission anticheataddition.bypass.anticheataddition_inventory.*

**Comment by Photon-GitHub** [comment]
Fixed in 8.5.2
