### ISSUE TITLE
Anti ESP not working 

### ISSUE THREAD

**Issue by TheTechnologyStudio** [Photon-GitHub/AntiCheatAddition#551]
Purpur 1.19.4

ESP enabled in config:

[13:44:19 ERROR]: [AntiCheatAddition] ESP | World faweregentempworld player tracking range could not be loaded, using default tracking range. 

error in console

let me know what other info you need.

**Comment by Photon-GitHub** [comment]
Well, ESP tried to load your "faweregentempworld" and could not find the player tracking range. This is not exactly a problem, it will just use the default one.

However, there should not be a error in console. Please use a service like hastebin or pastebin to show me the error.

**Comment by TheTechnologyStudio** [comment]
this is the only error and the anti esp is not working, all esps still work perfectly.

**Comment by Photon-GitHub** [comment]
Well, ESP can only hide information a normal player would not be able to get, like the equipment if standing behind a wall or the player itself if they are sneaking behind a wall. ESP cannot "disable" esp modules of cheat clients. Also, please make sure that neither the observer nor the observed player are OP or have bypass permissions.

**Comment by zPqguro03** [comment]
> Well, ESP can only hide information a normal player would not be able to get, like the equipment if standing behind a wall or the player itself if they are sneaking behind a wall. ESP cannot "disable" esp modules of cheat clients. Also, please make sure that neither the observer nor the observed player are OP or have bypass permissions.

Same error here, but there's also this exception [https://pastebin.com/sGUxUJgH](url) and anti-esp option is not working at all

**Comment by Photon-GitHub** [comment]
@zPqguro03 Please update ProtocolLib and make sure you use the latest Spigot 1.17.1. The protocol access is correct, but for some reason your ProtocolLib thinks that the packets to remove entities do not contain entities.

**Comment by zPqguro03** [comment]
> @zPqguro03 Please update ProtocolLib and make sure you use the latest Spigot 1.17.1. The protocol access is correct, but for some reason your ProtocolLib thinks that the packets to remove entities do not contain entities.

![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/20030855/fdce2cee-6c41-457c-bc2a-2dbd564ebe66)
![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/20030855/e94ad384-517d-4f43-a9a4-5a2de86bf9ed)

**Comment by Photon-GitHub** [comment]
I will look into it next week.

**Comment by Photon-GitHub** [comment]
I have not been able to reproduce this with normal spigot. Can you please tell me your exact setup and how you tested ESP?

**Comment by Photon-GitHub** [comment]
Closed due to inactivity. Feel free to post additional info and reopen.
