### ISSUE TITLE
Elytra + Firework issues

### ISSUE THREAD

**Issue by DasCanard** [Photon-GitHub/AntiCheatAddition#568]
https://share.richy.sh/23/08/7T7ju9.mp4

**Comment by DasCanard** [comment]
It actually affects every item that can be interacted with. (Rightclick with sword on ground = fp, sometimes also using bow, rod)

**Comment by Photon-GitHub** [comment]
This won't acually be fixed, as fixing it would introduce quite a few bypass possibilities. However, I will increase the vl decay so you would need to do this a very long time as a legit player to get high vls.

**Comment by Photon-GitHub** [comment]
Higher vl decay added in 8.8.2
