### ISSUE TITLE
Scaffold subcheck

### ISSUE THREAD

**Issue by Photon-GitHub** [Photon-GitHub/AntiCheatAddition#576]
Add a new subcheck to check for rotations that change the building direction (right downwards to left downwards and vice versa) instantaneously.

**Comment by Regomy** [comment]
Let me suggest =)

~ Add a check the moment you first set the block, many cheaters when turning on scafold get an instant head turn down, no matter where they were looking before, but in vanilla, you at least need time to aim at the block at the right angle.

~ I'm not sure about that, just thought of an idea. What if you add a little bit of velocity to the player during the build, i.e. flip him off a bit and watch his reaction?

**Comment by Photon-GitHub** [comment]
Added in 9.0.0.
