### ISSUE TITLE
Blocking thread

### ISSUE THREAD

**Issue by KevinPumpkin** [Photon-GitHub/AntiCheatAddition#582]
When using ESP, such errors often appear on the server, they are accompanied by a strong lag
https://pastebin.com/MDckDFQD

**Comment by Photon-GitHub** [comment]
Can you please add more information about your server?
What minecraft version are you using and what server software?

**Comment by KevinPumpkin** [comment]
> Can you please add more information about your server? What minecraft version are you using and what server software?

PaperSpigot 1.12.2

**Comment by Photon-GitHub** [comment]
Fixed in 9.1.0
