### ISSUE TITLE
Bstats error

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#584]
https://gist.github.com/Regomy/1064e024896c3552c287a20a8d2a191e
| ver: 9.0.0
| [15:02:39 INFO]: This server is running PandaSpigot version git-PandaSpigot-"858ab0f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)
[15:02:39 INFO]: Checking version, please wait...
[15:02:40 INFO]: You are running the latest version

**Comment by F3F5** [comment]
because this user is dumb and downloaded from blackmnecraft (rat site), ac is good.
