### ISSUE TITLE
Scaffold false flag.

### ISSUE THREAD

**Issue by rejomy** [Photon-GitHub/AntiCheatAddition#588]
https://youtu.be/HsML3q4Kev0

ver: 9.0.0
server: [15:51:43 INFO]: This server is running PandaSpigot version git-PandaSpigot-"858ab0f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)

logs: https://gist.github.com/Regomy/72223926a8896d8b0144cd7fa2d994ea (I'm sorry, but I do not know from what moment I started to flag, and since turning on ALL in the files, I'll block all the chat in the mine, I prsot simply took these logs from the console.)

**Comment by Photon-GitHub** [comment]
Please recheck on 9.1.4. It should appear more rarely. Even if it is not yet fixed, there are new log messages, so new logs would be helpful.
