### ISSUE TITLE
Scaffold False Flag

### ISSUE THREAD

**Issue by F3F5** [Photon-GitHub/AntiCheatAddition#589]
debugs/how

https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/5e6d0a9e-2352-4140-9698-5077ac7e423f

**Comment by F3F5** [comment]
![Screenshot_1](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/0757b5b3-8283-4c65-9d1b-abcdf292e30b)
last update, same situation

**Comment by Photon-GitHub** [comment]
Please recheck on 9.1.4. It should appear more rarely. Even if it is not yet fixed, there are new log messages, so new logs would be helpful.

**Comment by F3F5** [comment]
new issues
