### ISSUE TITLE
🔥* Config suggestions. *

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#591]
### Configurable number of violations.
**Instead of enable: true, I propose to allow the player to choose the number of violations per check**, for example: _violation: [-infinity;infinity] numbers < 0 disable the check, 0 is used for the check to work, for example, the check will be sent by verbose, not cause punishments. Numbers > 0 will cause n violations. That is, to turn it off, set it to less than zero, turn it on >= 0;_

> As you already answered me on discord, administrators can reduce the effectiveness of checks “out of ignorance,” but what if the check produces false indicators? We cannot weaken only it without weakening ALL checks for scaffold, inventory and other modules. And those who need to “LOOKE” these values will stupidly turn off the check or make it completely non-functional, increasing the number of “punishments violations” to a huge level, just to avoid false positives.

### Configurable time for violations to decay if the player no longer violates.
For example, you could add decay: 0.999, this is how much the player's violation per check will be multiplied when the player does not receive flags for that check.

**or do**

```
   decay:
     #Default(5)
     interval: 10
     #Default(10)
     delay: 10
     #Default(1)
     amount: 4
```

like in aac4

**Comment by Photon-GitHub** [comment]
I will not do this as I have explained before in the discord.
