### ISSUE TITLE
🏓* Verbose and alerts command. *

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#592]
**I would like to be able to choose who should be enabled to see violations and who should not.**

**Also, alerts can only send violations from punishments. That is, if there is an action in the config for 30 violations, we will receive a notification that the action for 30 violations has been completed.**

**And verbose will write every time a certain player fails a check.**

_I would like to see the ability to turn on and off the ability for other players to see these magazines, as well as make them look normal, and not just white._

> Here are the colors for /verbose and /alerts:
![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/87989875/a4dfb34f-cc57-4d81-bd16-c30e38890274)

**Comment by Photon-GitHub** [comment]
All of this can be done with exisiting ACA commands or the config.
