### ISSUE TITLE
ESP check isn't working (don't have op's)

### ISSUE THREAD

**Issue by F3F5** [Photon-GitHub/AntiCheatAddition#596]
![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/7203bf13-09a7-4583-bc9f-cb25b9ad556b)
![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/eaec4f73-3e6f-43f6-9293-b4a15765f227)

**Comment by Photon-GitHub** [comment]
Are you sure that both players are not op and have no bypass permissions?

**Comment by F3F5** [comment]
i'm sure

**Comment by Photon-GitHub** [comment]
Please use the FINEST debug setting for the log file and test again (with only 2 players, otherwise this will get very spammy).

**Comment by F3F5** [comment]
i dont have logs , i set fine

**Comment by F3F5** [comment]
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)

-Xms128M -XX:MaxRAMPercentage=90.0 -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true

esp not work with this JDK from falixnodes.net  (free server, to test plugin


but with other hosting it work good:
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

**Comment by F3F5** [comment]
![image](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/30be4b8c-92cd-4a0d-a4dd-176392493915)
and this

**Comment by Photon-GitHub** [comment]
If a particular JDK is the cause, I probably won’t fix the problem. The spammy error message has its own issue with #600 , so I will mosve that discussion there.

**Comment by F3F5** [comment]
so anticheat is useless.

**Comment by Photon-GitHub** [comment]
It works fine on my local test server with an up to date JDK. If your JDK causes my plugin to malfunction, I cannot fix that in my plugin even if I wanted to.
