### ISSUE TITLE
ESP long distance tablist

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#602]
https://youtu.be/gj9vpYLcr7I

check first moment, i think, server admin or you need to check max view distance and check if distance > maxViewDist showPlayer()

settings:
Esp:
  enabled: true
  interval_ticks: 2
  only_full_hide: false
  calculate_third_person_modes: false

**Comment by Photon-GitHub** [comment]
Only the tablist is a bug here. Players are hidden even on vanilla in the distance and I use the vanilla distances for that.

**Comment by Photon-GitHub** [comment]
It is not. But I don’t think the armor stuff is caused by ESP as ESP ignores the player themselves. I might need to test that though.

**Comment by F3F5** [comment]
so wtf with armor

**Comment by F3F5** [comment]
> Only the tablist is a bug here. Players are hidden even on vanilla in the distance and I use the vanilla distances for that.

any plans to fix it?

**Comment by Photon-GitHub** [comment]
Should be fixed in 9.1.4
