### ISSUE TITLE
ChestStealer bypass 

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#605]
> **ChestStealer code:**
```
public class ChestStealer extends Module {
    ModeSetting mode = new ModeSetting("Mode", "Normal", "Instant", "Normal");
    public ChestStealer() {
        super("ChestStealer", Category.PLAYER);
        addSettings(mode);
    }

    @Override
    public void onEvent(Event event) {
        if(!(event instanceof EventUpdate) || !(mc.currentScreen instanceof GuiChest)) {
            return;
        }

        ContainerChest chest = (ContainerChest) mc.thePlayer.openContainer;

        for(byte slot = 0; slot < chest.getLowerChestInventory().getSizeInventory(); slot++) {
            if(chest.getLowerChestInventory().getStackInSlot(slot) == null) {
                continue;
            }

            mc.playerController.windowClick(chest.windowId, slot, 0, 1, mc.thePlayer);

            if(mode.isCurrent("Normal")) {
                break;
            }
        }
    }
}
```

> **video:** https://youtu.be/_Io_AiTaQT0
> **logs:** [2024-05-13.log](https://github.com/Photon-GitHub/AntiCheatAddition/files/15296739/2024-05-13.log)

**Comment by Photon-GitHub** [comment]
Are you absolutely sure that you do not have bypass permissions? At least 3 different checks should pick that up, not to mention that someone tested this for the 9.0.0 release.

**Comment by Photon-GitHub** [comment]
Thank you. I think I will add some more debug messages in the next version that will help me find the problem why MultiInteraction and PerfectExit doesn't react.

**Comment by Photon-GitHub** [comment]
9.1.0 has a lot more debug messages. Please retest on that version so I have more log messages to work with. Please use the FINER log level, like before.

**Comment by Photon-GitHub** [comment]
This issue is kind of a mess. The latter comments are false positives and other stuff, so I will close this. Please report any remaining problems in their own issues.
