### ISSUE TITLE
ACA destroy schedulers?

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#606]
> This server is running PandaSpigot version git-PandaSpigot-"858ab0f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)
> Soup, Chest, AutoMessage, WorldEdit, ViaVersion, ProtocolLib, WorldGuard, LuckPerms, packetevents, Vault, TAB, Essentials
> video: https://youtu.be/pxEAxOBI0Uc
> automessage cmd code:
```
package me.rejomy.automessage.command;

import me.rejomy.automessage.Main;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

public class AutoMessageCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if(args.length == 0) {
            sender.sendMessage("run нахуй");
            Bukkit.getScheduler().scheduleSyncDelayedTask(Main.getInstance(), () -> {
                Bukkit.broadcastMessage("я выполнился1");
            }, 30);

            Bukkit.getScheduler().scheduleSyncRepeatingTask(Main.getInstance(), () -> {
                Bukkit.broadcastMessage("я я тоже");
            }, 60, 60);
            return false;
        }

        return false;
    }

}
```

**Comment by F3F5** [comment]
![image2](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/ebc2d14f-1636-453f-a080-0c1d2b89450f)

**Comment by F3F5** [comment]
without aca, it work properly

**Comment by F3F5** [comment]
but it work on 1.12.2 with aca

**Comment by F3F5** [comment]
plugin to test: https://workupload.com/file/sMUGgLB8uEa

**Comment by F3F5** [comment]
THATS WHY MY SERVER CANT RUN DUEL MATCH, BECAUSE OF THIS PLUGIN

**Comment by F3F5** [comment]
@Photon-GitHub

**Comment by F3F5** [comment]
![Screenshot_1](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/4fe7c78e-8e18-4966-bc29-f20c2bbb7403)
SCHEDULERS NOT WORK, VERSION WITHOUT PACKETEVENTS, MY DUEL CAN'T START, BUT IF I DELETING ACA I SEE MY LOCAL TIME PLACEHOLDERS AND OTHER MOMENTS

**Comment by F3F5** [comment]
not work because uses runable https://github.com/aBooDyy/LocalTime-Expansion/blob/master/src/main/java/net/aboodyy/localtime/DateManager.java

**Comment by Photon-GitHub** [comment]
I have no idea what is causing that. However, you can retry on 9.1.0 as I have checked to only use modern scheduler methods, remove a bukkitrunnable and cancel a bukkittask instead of a taskid. I don't know if that will help.

**Comment by F3F5** [comment]
did you confirmed that bug?

**Comment by Photon-GitHub** [comment]
No. I cannot reproduce it.

**Comment by F3F5** [comment]
> No. I cannot reproduce it.

i can join to vc and can proof it.

**Comment by F3F5** [comment]
it work only for 1.8

**Comment by Photon-GitHub** [comment]
I know you have the problem, but I cannot reproduce it locally. Also, I have no idea what exactly is causing it, as I do not cancel any tasks, just schedule them. For some reason 1.8.8 has a problem with that, all other versions do not.

**Comment by F3F5** [comment]
![Screenshot_9](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/7bc01b74-4011-45ea-8639-2c3fab0d213d)
seems work after new update

**Comment by F3F5** [comment]
![Screenshot_13](https://github.com/Photon-GitHub/AntiCheatAddition/assets/108226177/5fde49d8-3614-44fb-8805-0f3abdbf4a09)
for some reason, it breaks the plugin during the day and you can't run it anywhere, but then it works again after some hours

**Comment by F3F5** [comment]
@Photon-GitHub
