### ISSUE TITLE
ESP Visibility through non-full blocks

### ISSUE THREAD

**Issue by Baba1408** [Photon-GitHub/AntiCheatAddition#616]
The players are visible through the full blocks, even if this may be inconvenient depending on the type of server, I think it would be better not to make a difference as this could result in better performance in my opinion (this could be a configurable option).

Server version : Paper 1.8.8
AntiCheatAddition version : 9.1.3

> https://youtu.be/eB9M4ZuiR3g?si=jctGYCxV7RgL0sB2&t=40

**Comment by Janmm14** [comment]
Adding non-full blocks into the algorithm requires a addig a check for every non-full block, I am not sure whether photon is willing to add and maintain this.

**Comment by Photon-GitHub** [comment]
This is expected behavior. Handling partial blocks would require raytracing which would decrease performance by orders of magnitudes.
