### ISSUE TITLE
ESP non-full block is between the players

### ISSUE THREAD

**Issue by Baba1408** [Photon-GitHub/AntiCheatAddition#617]
If a non-full block is between the players, Anti ESP doesn't work even if there are full blocks (this only happens at a certain distance, so I don't really understand).

Server version : Paper 1.8.8
AntiCheatAddition version : 9.1.3

> https://youtu.be/eB9M4ZuiR3g?si=wGSQCWDpXgGqmdTs&t=70

**Comment by Janmm14** [comment]
The current ESP check does not check every block between players in order to not cripple server performance, it checks for blocks near either player and at some points inbetween both players (like in the middle between).

**Comment by Photon-GitHub** [comment]
That is expected behaviour. It is a tradeoff between checking more blocks and performance. Especially non-full blocks would need raytracing which is way too computationally expensive.
