### ISSUE TITLE
🤫 | Scaffold Average falses when shifting

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#626]
> https://youtu.be/N7aEv8VWg6E
> [2024-05-22.log](https://github.com/Photon-GitHub/AntiCheatAddition/files/15403493/2024-05-22.log)

**Comment by Photon-GitHub** [comment]
Given how often you fall down with your building method, I will not support it and just refer to the config here:

  # This is the main delay Scaffold enforces if a player builds too fast.
  # This covers all common building techniques and players. Still, you might need to reduce this value if you have
  # very strong players with absurd building techniques on your server (in milliseconds).
  placement_delay: 238
