### ISSUE TITLE
🟡 | ChestStealer bypass with high delay between clicks

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#627]
> [2024-05-22.log](https://github.com/Photon-GitHub/AntiCheatAddition/files/15403579/2024-05-22.log)
> https://youtu.be/kgJHR96VITw

**Comment by Janmm14** [comment]
this looks as fast as a human would be, so there is not much benefit of using the cheatand also harder to differentiate human and cheat.

**Comment by Janmm14** [comment]
I never said "human eye can see" I said, the speed in the video is something a human can achieve.

If a cheat is just as good as a good player, it is not a bypass.

**Comment by Photon-GitHub** [comment]
At least this particular cheat without randomization should be detected in 3.1.5
