### ISSUE TITLE
🌵🌵🌵🌵please fix the anticactus🌵🌵🌵

### ISSUE THREAD

**Issue by F3F5** [Photon-GitHub/AntiCheatAddition#630]
none of the anti-cheat has it, no one will fix it, but the photon will be able to 🇷🇺
liquidbounce anticactus 
****
🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵🌵

**Comment by Photon-GitHub** [comment]
This is a movement check. Autocactus just expands the collision box of a cactus. I will not include movement checks.
