### ISSUE TITLE
🟢 | Suggestion -> PingSpoof check

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#631]
Let's please discuss. How would we detect it? Well, uh. the first thing that comes to mind is normal high-pitch movements. 

If a player doesn't lag but has a high ping, is it cheating?

Can we check the blink by doing that? Let's say. A player during a blink can only delay their own packets and the server packets are processed, meaning if a player hits a player in "that player's current position" it's probably a blink. Since the player should have hit him in his old position "before blinking".

Translated with DeepL.com (free version)

**Comment by Photon-GitHub** [comment]
I have had a pingspoof check for a long time, but it has always been quite unreliable and very maintenance intensive. There have been multiple times where minecraft changed the packets. Thus, I do not think I will readd that check.
