### ISSUE TITLE
false perfect rotation flag

### ISSUE THREAD

**Issue by MahadRegent** [Photon-GitHub/AntiCheatAddition#640]
When using Pojavlauncher mobile phone perfect rotation false flagging when hitting.

**Comment by Photon-GitHub** [comment]
I am unsure what your setup is. Do you use floodgate? If so, all floodgate users should be bypassed. Besides, ACA does not guarantee that some unofficial lauchers will not be detected.

**Comment by F3F5** [comment]
https://pojavlauncherteam.github.io/

**Comment by Janmm14** [comment]
Very likely problem of pojavlauncher or whatever they do to have good touch support on mc java

**Comment by Photon-GitHub** [comment]
I will not officially support a touch-based minecraft launcher, that probably has all kinds of different subtle protocol changes. If you really want to have players with that on your server, disable the modules accordingly.
