### ISSUE TITLE
Scaffold Bypass

### ISSUE THREAD

**Issue by F3F5** [Photon-GitHub/AntiCheatAddition#646]
In general, download LuquidBounce 1.8.9 from the official site, in the settings autosetting set hypixel mode, enable scaffold (sprint is not necessary). 
https://streamable.com/ypb2mv 
in case the video at the link stops working, the video can be downloaded here: https://workupload.com/file/GApUS7NtAXz
this video's a scaffold, end with the logs.
full logs: https://pastebin.com/wxnjM1p5

[AntiCheatAddition] Version: 9.1.4
[19:54:19 INFO]: This server is running PandaSpigot version git-PandaSpigot-119 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)

**Comment by Photon-GitHub** [comment]
Yes, slow Scaffolds that are achievable by legit players may not be detected. LiquidBounce is quite good at simulating such a player. I will probably not be able to fix that because it would otherwise cause false positives for good players.
