### ISSUE TITLE
Stepping due to slide when opening inventory causes false positive

### ISSUE THREAD

**Issue by Janmm14** [Photon-GitHub/AntiCheatAddition#647]
Issue by MILK on discord who feels creating a github account is too much work while not even having purcharsed the plugin.

https://github.com/Photon-GitHub/AntiCheatAddition/assets/3533175/4c246096-2598-4433-b480-7e557be99faa

**Comment by Photon-GitHub** [comment]
Should be fixed in 9.1.5. This was only an issue on 1.8.8 anyways.
