### ISSUE TITLE
False flag PacketAnalysis

### ISSUE THREAD

**Issue by MahadRegent** [Photon-GitHub/AntiCheatAddition#658]
Hello, i need to show you a false flag with packetanalysis. 
Just donwload a pojavlauncher and join to the server , and do moving of camera. And you will be see a falses of this.

**Comment by Janmm14** [comment]
This will likely not be fixable without just disabling detection. pojavlauncher changes stuff from minecraft java that shouldn't be changed apparantly.

**Comment by Photon-GitHub** [comment]
Indeed. I do not support custom launchers if they change anything about the movement code in Minecraft. Given that this launcher allows touch-based inputs, that is clearly the case here. If you really need to support the launcher, please disable the check.
