### ISSUE TITLE
the new check is falsely triggered

### ISSUE THREAD

**Issue by ghost** [Photon-GitHub/AntiCheatAddition#662]
https://github.com/user-attachments/assets/637f6f8e-a0b1-45a9-af42-90fb3beaba8d

**Comment by michaelkozloov** [comment]
https://github.com/user-attachments/assets/b0bb1820-f7b7-4729-a8b3-ac8db12b5f57

**Comment by Photon-GitHub** [comment]
Fixed in the official release.
