### ISSUE TITLE
impossiblechat not working if player not sprinting 

### ISSUE THREAD

**Issue by michaelkozloov** [Photon-GitHub/AntiCheatAddition#663]
when I run fast on a sprint, everything is fine, and when I drive slowly without sprinting, it does not detect. I checked on the cheat luquidbounce 1.8.9

**Comment by Janmm14** [comment]
the check for impossible chat is simple and cannot be improved without exorbitant amount of effort due to palyers not immediately stopping when releasing key or velocity beng applied etc etc etc
