### ISSUE TITLE
🟢 | Particle hider.

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#667]
# Hide particle on the entity after they get effect.

Its sometimes bad, cuz players will not understand what is the effect on the entity, but for bedwars its useful, for example when player drank power potion, client can send me message or draw about his name power potion effect (hacker client can get in from entity particles (set when we send metadata packet, on 1.8.8 core index with effect info in metadata is 7) or from getActivePotionEffects)

**Comment by Photon-GitHub** [comment]
I think I will merge this with #666 as that is the same thing, but without the visibility check. You can just give an effect without particles and then the PotionHider will function.
